version: "3.7"
services:
  api:
    image: "video_websocket:latest"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /start.sh

  redis:
    image: "redis:7.0.4"
    # TODO: Add disk storage?

networks:
  default:
    external:
      name: $NETWORK_NAME