version: "3.7"
services:
  api:
    image: "video_websocket:latest"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /start.sh

networks:
  default:
    external:
      name: $NETWORK_NAME